// publisher.config.mjs
// Generated by Publisher. Do not change publisherVersion manually.

// --- PublisherContent type (reference copy) ---
/**
 * @typedef {Object} PublisherContent
 * @property {string} [title]
 * @property {string} [body]
 * @property {string} caption - Required. The text posted to social media.
 * @property {string[]} [tags]
 */

export const publisherVersion = 1

export default {
  // Template slugs this project uses, pinned to a specific version.
  templates: {
      "quote-short": 1,
      "quote-wide": 1
  },

  // Social channels to publish to.
  channels: ['instagram', 'facebook', 'linkedin'],

  // Content adapter: receives a file path, returns PublisherContent.
  // Default: reads a JSON file with { title?, caption, body?, tags? }
  adapter: async (filePath) => {
    const { readFile } = await import('fs/promises')
    const raw = await readFile(filePath, 'utf-8')
    const data = JSON.parse(raw)
    return {
      title:   data.title,
      body:    data.body,
      caption: data.caption ?? '',
      tags:    data.tags ?? [],
    }
  },
}
